name: PR Linter
on: [pull_request]
jobs:
  danger:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile.danger
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - run: |
          # the personal token is public, this is ok, base64 encode to avoid tripping Github
          TOKEN=$(echo -n Z2hwX01rSWxjcllwWDE3NU1GR3pTaURIcWdnYTJxQlFybjFkZlhUMA== | base64 --decode)
          DANGER_GITHUB_API_TOKEN=$TOKEN bundle exec danger --verbose